name: Deploy Vite App to DigitalOcean

on:
  push:
    branches:
      - main # Deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify Node.js version compatible with Vite

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Vite App
        run: npm run build
        working-directory: ./frontend

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Copy Built Files to Droplet
        run: |
          ssh-keyscan -H 137.184.119.191 >> ~/.ssh/known_hosts
          scp -r dist/* wesley@137.184.119.191:/home/wesley/deployment
        working-directory: ./frontend

      - name: Restart application on Droplet
        run: ssh wesley@137.184.119.191 "cd /deployment && ./deploy.sh"
